---
title: "R Notebook"
output: html_notebook
---
```{r}
data = read.csv("/Users/lazzataibekova/Dropbox (OIST)/varroa microbiome/DE_varroa_microbiome.csv")
data

```
###Varroa vs  Microbiome
```{r}
plot(data$V_DE, data$M_DE, xlab = "Varroa genes", ylab = "Microbiome genes", main = "Total number of DEG")
cor(data$V_DE, data$M_DE)
```
#Up-regulated genes
```{r}
plot(data$V_up.regulated, data$M_up.regulated, xlab = "Varroa genes", ylab = "Microbiome genes", main = "Number of up-regulated genes")
cor(data$V_up.regulated, data$M_up.regulated)
```
#Down-regulated 
```{r}
plot(data$V_down.regulated, data$M_down.regulated, xlab = "Varroa genes", ylab = "Microbiome genes", main = "Number of down-regulated genes")
cor(data$V_down.regulated, data$M_down.regulated)
```
###Re-mapped Varroa vs Microbiome 

```{r}
plot(data$V2_DE, data$M_DE,  xlab = "Varroa genes", ylab = "Microbiome genes", main = "Total number of DEG (re-mapped)")
cor(data$V2_DE, data$M_DE)
```
#Up-regulated genes
```{r}
plot(data$V2_up.regulated, data$M_up.regulated,  xlab = "Varroa genes", ylab = "Microbiome genes", main = "Number of up-regulated genes (re-mapped)")
cor(data$V2_up.regulated, data$M_up.regulated)
```
#Down-regulated genes
```{r}
plot(data$V2_down.regulated, data$M_down.regulated,  xlab = "Varroa genes", ylab = "Microbiome genes", main = "Number of down-regulated genes (re-mapped)")
cor(data$V2_down.regulated, data$M_down.regulated)
```
###Gene-level analysis 
```{r}
plot(data$V2_DE, data$V_gene_DE, xlab = "Re-mapped DE Varroa genes", ylab = "Gene-level DE VArroa", main = "Varroa DE vs Gene-level DE")
cor(data$V2_DE, data$V_gene_DE)
```

#Microbiome vs Varroa (gene-level)
```{r}
plot(data$V_gene_DE, data$M_DE, xlab = "Gene-level DE Varroa", ylab ="Microbiome DE", main = "Varroa Gene-level DE vs Microbiome DE")
cor(data$V_gene_DE, data$M_DE)
```
```{r}
plot(data$V_gene_up.regulated, data$M_up.regulated, xlab = "Gene-level up-regulated VArroa", ylab = "Microbiome up-regulated", main = "Varroa Gene-level vs Microbiome")
cor(data$V_gene_up.regulated, data$M_up.regulated)
```

```{r}
plot(data$V_gene_down.regulated, data$M_down.regulated, xlab = "Gene-level down-regulated VArroa", ylab = "Microbiome down-regulated", main = "Varroa Gene-level vs Microbiome")
cor(data$V_gene_down.regulated, data$M_down.regulated)
```